name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Or your main branch name
    paths:
      - 'backend/**' # Only run when backend code changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies & Deploy
        working-directory: ./backend # Change directory to backend
        run: |
          npm install
          npx wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
